[config]
schemaVersion = "0.0.1"


[package]
namespace = "zannc"
name = "Practical_Gods"
versionNumber = "1.0.0"
description = "Ever felt like Artemis was a bit useless? Wanted to see her drop as a regular god? This mod adds in 4 of Artemis' Hades 1 boons, and allows her to spawn like a regular god, alongside adding some boons to Hermes to expand his arsenal"
websiteUrl = "https://github.com/zanncdwbl/zannc-Practical_Gods"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.44"
SGG_Modding-ModUtil = "4.0.0"
SGG_Modding-ENVY = "1.1.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-SJSON = "1.0.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

[[build.copy]]
source = "./packages"
target = "./plugins_data"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
