[config]
schemaVersion = "0.0.1"


[package]
namespace = "zannc"
name = "BoonAdditions"
versionNumber = "0.0.1"
description = ""
websiteUrl = "https://github.com/zanncdwbl/zannc-BoonAdditions"
containsNsfwContent = false

[package.dependencies]
SGG_Modding-ModUtil = "4.0.0"
Hell2Modding-Hell2Modding = "1.0.41"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-ENVY = "1.1.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

[[build.copy]]
source = "./packages"
target = "./plugins_data"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
